// Code generated by go-swagger; DO NOT EDIT.

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DaemonOptionsOKCode is the HTTP code returned for type DaemonOptionsOK
const DaemonOptionsOKCode int = 200

/*DaemonOptionsOK Sucessful operation

swagger:response daemonOptionsOK
*/
type DaemonOptionsOK struct {
}

// NewDaemonOptionsOK creates DaemonOptionsOK with default headers values
func NewDaemonOptionsOK() *DaemonOptionsOK {

	return &DaemonOptionsOK{}
}

// WriteResponse to the client
func (o *DaemonOptionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DaemonOptionsServiceUnavailableCode is the HTTP code returned for type DaemonOptionsServiceUnavailable
const DaemonOptionsServiceUnavailableCode int = 503

/*DaemonOptionsServiceUnavailable Service unavailable

swagger:response daemonOptionsServiceUnavailable
*/
type DaemonOptionsServiceUnavailable struct {
}

// NewDaemonOptionsServiceUnavailable creates DaemonOptionsServiceUnavailable with default headers values
func NewDaemonOptionsServiceUnavailable() *DaemonOptionsServiceUnavailable {

	return &DaemonOptionsServiceUnavailable{}
}

// WriteResponse to the client
func (o *DaemonOptionsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
