// Code generated by go-swagger; DO NOT EDIT.

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DaemonInfoHandlerFunc turns a function with the right signature into a daemon info handler
type DaemonInfoHandlerFunc func(DaemonInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DaemonInfoHandlerFunc) Handle(params DaemonInfoParams) middleware.Responder {
	return fn(params)
}

// DaemonInfoHandler interface for that can handle valid daemon info params
type DaemonInfoHandler interface {
	Handle(DaemonInfoParams) middleware.Responder
}

// NewDaemonInfo creates a new http.Handler for the daemon info operation
func NewDaemonInfo(ctx *middleware.Context, handler DaemonInfoHandler) *DaemonInfo {
	return &DaemonInfo{Context: ctx, Handler: handler}
}

/*DaemonInfo swagger:route GET /daemon daemon daemonInfo

Get daemon information

Returns information about P2P daemon

*/
type DaemonInfo struct {
	Context *middleware.Context
	Handler DaemonInfoHandler
}

func (o *DaemonInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDaemonInfoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
