// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SwarmOptionsOKCode is the HTTP code returned for type SwarmOptionsOK
const SwarmOptionsOKCode int = 200

/*SwarmOptionsOK Sucessful operation

swagger:response swarmOptionsOK
*/
type SwarmOptionsOK struct {
}

// NewSwarmOptionsOK creates SwarmOptionsOK with default headers values
func NewSwarmOptionsOK() *SwarmOptionsOK {

	return &SwarmOptionsOK{}
}

// WriteResponse to the client
func (o *SwarmOptionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SwarmOptionsBadRequestCode is the HTTP code returned for type SwarmOptionsBadRequest
const SwarmOptionsBadRequestCode int = 400

/*SwarmOptionsBadRequest Bad request

swagger:response swarmOptionsBadRequest
*/
type SwarmOptionsBadRequest struct {
}

// NewSwarmOptionsBadRequest creates SwarmOptionsBadRequest with default headers values
func NewSwarmOptionsBadRequest() *SwarmOptionsBadRequest {

	return &SwarmOptionsBadRequest{}
}

// WriteResponse to the client
func (o *SwarmOptionsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// SwarmOptionsServiceUnavailableCode is the HTTP code returned for type SwarmOptionsServiceUnavailable
const SwarmOptionsServiceUnavailableCode int = 503

/*SwarmOptionsServiceUnavailable Service unavailable

swagger:response swarmOptionsServiceUnavailable
*/
type SwarmOptionsServiceUnavailable struct {
}

// NewSwarmOptionsServiceUnavailable creates SwarmOptionsServiceUnavailable with default headers values
func NewSwarmOptionsServiceUnavailable() *SwarmOptionsServiceUnavailable {

	return &SwarmOptionsServiceUnavailable{}
}

// WriteResponse to the client
func (o *SwarmOptionsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
