// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SwarmOptionsHandlerFunc turns a function with the right signature into a swarm options handler
type SwarmOptionsHandlerFunc func(SwarmOptionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SwarmOptionsHandlerFunc) Handle(params SwarmOptionsParams) middleware.Responder {
	return fn(params)
}

// SwarmOptionsHandler interface for that can handle valid swarm options params
type SwarmOptionsHandler interface {
	Handle(SwarmOptionsParams) middleware.Responder
}

// NewSwarmOptions creates a new http.Handler for the swarm options operation
func NewSwarmOptions(ctx *middleware.Context, handler SwarmOptionsHandler) *SwarmOptions {
	return &SwarmOptions{Context: ctx, Handler: handler}
}

/*SwarmOptions swagger:route POST /swarm swarm swarmOptions

Update swarm keys

Add new crypto keys to an existing swarm

*/
type SwarmOptions struct {
	Context *middleware.Context
	Handler SwarmOptionsHandler
}

func (o *SwarmOptions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSwarmOptionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
