// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/subutai-io/p2p/rest/models"
)

// SwarmStatusOKCode is the HTTP code returned for type SwarmStatusOK
const SwarmStatusOKCode int = 200

/*SwarmStatusOK Sucessful operation

swagger:response swarmStatusOK
*/
type SwarmStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.InstanceDetails `json:"body,omitempty"`
}

// NewSwarmStatusOK creates SwarmStatusOK with default headers values
func NewSwarmStatusOK() *SwarmStatusOK {

	return &SwarmStatusOK{}
}

// WithPayload adds the payload to the swarm status o k response
func (o *SwarmStatusOK) WithPayload(payload *models.InstanceDetails) *SwarmStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the swarm status o k response
func (o *SwarmStatusOK) SetPayload(payload *models.InstanceDetails) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SwarmStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SwarmStatusNotFoundCode is the HTTP code returned for type SwarmStatusNotFound
const SwarmStatusNotFoundCode int = 404

/*SwarmStatusNotFound Hash not found

swagger:response swarmStatusNotFound
*/
type SwarmStatusNotFound struct {
}

// NewSwarmStatusNotFound creates SwarmStatusNotFound with default headers values
func NewSwarmStatusNotFound() *SwarmStatusNotFound {

	return &SwarmStatusNotFound{}
}

// WriteResponse to the client
func (o *SwarmStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// SwarmStatusServiceUnavailableCode is the HTTP code returned for type SwarmStatusServiceUnavailable
const SwarmStatusServiceUnavailableCode int = 503

/*SwarmStatusServiceUnavailable Service unavailable

swagger:response swarmStatusServiceUnavailable
*/
type SwarmStatusServiceUnavailable struct {
}

// NewSwarmStatusServiceUnavailable creates SwarmStatusServiceUnavailable with default headers values
func NewSwarmStatusServiceUnavailable() *SwarmStatusServiceUnavailable {

	return &SwarmStatusServiceUnavailable{}
}

// WriteResponse to the client
func (o *SwarmStatusServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
