// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/subutai-io/p2p/rest/models"
)

// NewSwarmOptionsParams creates a new SwarmOptionsParams object
// no default values defined in spec.
func NewSwarmOptionsParams() SwarmOptionsParams {

	return SwarmOptionsParams{}
}

// SwarmOptionsParams contains all the bound params for the swarm options operation
// typically these are obtained from a http.Request
//
// swagger:parameters SwarmOptions
type SwarmOptionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Instance configuration
	  Required: true
	  In: body
	*/
	Body *models.Key
	/*Instance hash
	  Required: true
	  In: query
	*/
	Hash string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSwarmOptionsParams() beforehand.
func (o *SwarmOptionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Key
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {

			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	qHash, qhkHash, _ := qs.GetOK("hash")
	if err := o.bindHash(qHash, qhkHash, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SwarmOptionsParams) bindHash(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("hash", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("hash", "query", raw); err != nil {
		return err
	}

	o.Hash = raw

	return nil
}
