// Code generated by go-swagger; DO NOT EDIT.

package swarm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SwarmStatusHandlerFunc turns a function with the right signature into a swarm status handler
type SwarmStatusHandlerFunc func(SwarmStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SwarmStatusHandlerFunc) Handle(params SwarmStatusParams) middleware.Responder {
	return fn(params)
}

// SwarmStatusHandler interface for that can handle valid swarm status params
type SwarmStatusHandler interface {
	Handle(SwarmStatusParams) middleware.Responder
}

// NewSwarmStatus creates a new http.Handler for the swarm status operation
func NewSwarmStatus(ctx *middleware.Context, handler SwarmStatusHandler) *SwarmStatus {
	return &SwarmStatus{Context: ctx, Handler: handler}
}

/*SwarmStatus swagger:route GET /swarm swarm swarmStatus

Display instance information

Display detailed information about specified instance

*/
type SwarmStatus struct {
	Context *middleware.Context
	Handler SwarmStatusHandler
}

func (o *SwarmStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSwarmStatusParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
