// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/subutai-io/p2p/rest/restapi/operations/daemon"
	"github.com/subutai-io/p2p/rest/restapi/operations/instances"
	"github.com/subutai-io/p2p/rest/restapi/operations/swarm"
)

// NewP2pAPI creates a new P2p instance
func NewP2pAPI(spec *loads.Document) *P2pAPI {
	return &P2pAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		XMLConsumer:         runtime.XMLConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		XMLProducer:         runtime.XMLProducer(),
		InstancesCloseInstanceHandler: instances.CloseInstanceHandlerFunc(func(params instances.CloseInstanceParams) middleware.Responder {
			return middleware.NotImplemented("operation InstancesCloseInstance has not yet been implemented")
		}),
		InstancesCreateInstanceHandler: instances.CreateInstanceHandlerFunc(func(params instances.CreateInstanceParams) middleware.Responder {
			return middleware.NotImplemented("operation InstancesCreateInstance has not yet been implemented")
		}),
		DaemonDaemonInfoHandler: daemon.DaemonInfoHandlerFunc(func(params daemon.DaemonInfoParams) middleware.Responder {
			return middleware.NotImplemented("operation DaemonDaemonInfo has not yet been implemented")
		}),
		DaemonDaemonOptionsHandler: daemon.DaemonOptionsHandlerFunc(func(params daemon.DaemonOptionsParams) middleware.Responder {
			return middleware.NotImplemented("operation DaemonDaemonOptions has not yet been implemented")
		}),
		InstancesListInstancesHandler: instances.ListInstancesHandlerFunc(func(params instances.ListInstancesParams) middleware.Responder {
			return middleware.NotImplemented("operation InstancesListInstances has not yet been implemented")
		}),
		SwarmSwarmOptionsHandler: swarm.SwarmOptionsHandlerFunc(func(params swarm.SwarmOptionsParams) middleware.Responder {
			return middleware.NotImplemented("operation SwarmSwarmOptions has not yet been implemented")
		}),
		SwarmSwarmStatusHandler: swarm.SwarmStatusHandlerFunc(func(params swarm.SwarmStatusParams) middleware.Responder {
			return middleware.NotImplemented("operation SwarmSwarmStatus has not yet been implemented")
		}),
	}
}

/*P2pAPI Subutai P2P operations */
type P2pAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer
	// XMLConsumer registers a consumer for a "application/xml" mime type
	XMLConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer
	// XMLProducer registers a producer for a "application/xml" mime type
	XMLProducer runtime.Producer

	// InstancesCloseInstanceHandler sets the operation handler for the close instance operation
	InstancesCloseInstanceHandler instances.CloseInstanceHandler
	// InstancesCreateInstanceHandler sets the operation handler for the create instance operation
	InstancesCreateInstanceHandler instances.CreateInstanceHandler
	// DaemonDaemonInfoHandler sets the operation handler for the daemon info operation
	DaemonDaemonInfoHandler daemon.DaemonInfoHandler
	// DaemonDaemonOptionsHandler sets the operation handler for the daemon options operation
	DaemonDaemonOptionsHandler daemon.DaemonOptionsHandler
	// InstancesListInstancesHandler sets the operation handler for the list instances operation
	InstancesListInstancesHandler instances.ListInstancesHandler
	// SwarmSwarmOptionsHandler sets the operation handler for the swarm options operation
	SwarmSwarmOptionsHandler swarm.SwarmOptionsHandler
	// SwarmSwarmStatusHandler sets the operation handler for the swarm status operation
	SwarmSwarmStatusHandler swarm.SwarmStatusHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *P2pAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *P2pAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *P2pAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *P2pAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *P2pAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *P2pAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *P2pAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the P2pAPI
func (o *P2pAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.XMLConsumer == nil {
		unregistered = append(unregistered, "XMLConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.XMLProducer == nil {
		unregistered = append(unregistered, "XMLProducer")
	}

	if o.InstancesCloseInstanceHandler == nil {
		unregistered = append(unregistered, "instances.CloseInstanceHandler")
	}

	if o.InstancesCreateInstanceHandler == nil {
		unregistered = append(unregistered, "instances.CreateInstanceHandler")
	}

	if o.DaemonDaemonInfoHandler == nil {
		unregistered = append(unregistered, "daemon.DaemonInfoHandler")
	}

	if o.DaemonDaemonOptionsHandler == nil {
		unregistered = append(unregistered, "daemon.DaemonOptionsHandler")
	}

	if o.InstancesListInstancesHandler == nil {
		unregistered = append(unregistered, "instances.ListInstancesHandler")
	}

	if o.SwarmSwarmOptionsHandler == nil {
		unregistered = append(unregistered, "swarm.SwarmOptionsHandler")
	}

	if o.SwarmSwarmStatusHandler == nil {
		unregistered = append(unregistered, "swarm.SwarmStatusHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *P2pAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *P2pAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *P2pAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *P2pAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		case "application/xml":
			result["application/xml"] = o.XMLConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *P2pAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		case "application/xml":
			result["application/xml"] = o.XMLProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *P2pAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the p2p API
func (o *P2pAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *P2pAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/instance"] = instances.NewCloseInstance(o.context, o.InstancesCloseInstanceHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/instance"] = instances.NewCreateInstance(o.context, o.InstancesCreateInstanceHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/daemon"] = daemon.NewDaemonInfo(o.context, o.DaemonDaemonInfoHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/daemon"] = daemon.NewDaemonOptions(o.context, o.DaemonDaemonOptionsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/instance"] = instances.NewListInstances(o.context, o.InstancesListInstancesHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/swarm"] = swarm.NewSwarmOptions(o.context, o.SwarmSwarmOptionsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/swarm"] = swarm.NewSwarmStatus(o.context, o.SwarmSwarmStatusHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *P2pAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *P2pAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *P2pAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *P2pAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
