// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CloseInstanceOKCode is the HTTP code returned for type CloseInstanceOK
const CloseInstanceOKCode int = 200

/*CloseInstanceOK Sucessfully created

swagger:response closeInstanceOK
*/
type CloseInstanceOK struct {
}

// NewCloseInstanceOK creates CloseInstanceOK with default headers values
func NewCloseInstanceOK() *CloseInstanceOK {

	return &CloseInstanceOK{}
}

// WriteResponse to the client
func (o *CloseInstanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CloseInstanceBadRequestCode is the HTTP code returned for type CloseInstanceBadRequest
const CloseInstanceBadRequestCode int = 400

/*CloseInstanceBadRequest Bad request

swagger:response closeInstanceBadRequest
*/
type CloseInstanceBadRequest struct {
}

// NewCloseInstanceBadRequest creates CloseInstanceBadRequest with default headers values
func NewCloseInstanceBadRequest() *CloseInstanceBadRequest {

	return &CloseInstanceBadRequest{}
}

// WriteResponse to the client
func (o *CloseInstanceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CloseInstanceServiceUnavailableCode is the HTTP code returned for type CloseInstanceServiceUnavailable
const CloseInstanceServiceUnavailableCode int = 503

/*CloseInstanceServiceUnavailable Service unavailable

swagger:response closeInstanceServiceUnavailable
*/
type CloseInstanceServiceUnavailable struct {
}

// NewCloseInstanceServiceUnavailable creates CloseInstanceServiceUnavailable with default headers values
func NewCloseInstanceServiceUnavailable() *CloseInstanceServiceUnavailable {

	return &CloseInstanceServiceUnavailable{}
}

// WriteResponse to the client
func (o *CloseInstanceServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
