// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateInstanceOKCode is the HTTP code returned for type CreateInstanceOK
const CreateInstanceOKCode int = 200

/*CreateInstanceOK Sucessfully created

swagger:response createInstanceOK
*/
type CreateInstanceOK struct {
}

// NewCreateInstanceOK creates CreateInstanceOK with default headers values
func NewCreateInstanceOK() *CreateInstanceOK {

	return &CreateInstanceOK{}
}

// WriteResponse to the client
func (o *CreateInstanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CreateInstanceBadRequestCode is the HTTP code returned for type CreateInstanceBadRequest
const CreateInstanceBadRequestCode int = 400

/*CreateInstanceBadRequest Bad request

swagger:response createInstanceBadRequest
*/
type CreateInstanceBadRequest struct {
}

// NewCreateInstanceBadRequest creates CreateInstanceBadRequest with default headers values
func NewCreateInstanceBadRequest() *CreateInstanceBadRequest {

	return &CreateInstanceBadRequest{}
}

// WriteResponse to the client
func (o *CreateInstanceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateInstanceServiceUnavailableCode is the HTTP code returned for type CreateInstanceServiceUnavailable
const CreateInstanceServiceUnavailableCode int = 503

/*CreateInstanceServiceUnavailable Service unavailable

swagger:response createInstanceServiceUnavailable
*/
type CreateInstanceServiceUnavailable struct {
}

// NewCreateInstanceServiceUnavailable creates CreateInstanceServiceUnavailable with default headers values
func NewCreateInstanceServiceUnavailable() *CreateInstanceServiceUnavailable {

	return &CreateInstanceServiceUnavailable{}
}

// WriteResponse to the client
func (o *CreateInstanceServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
