// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateInstanceHandlerFunc turns a function with the right signature into a create instance handler
type CreateInstanceHandlerFunc func(CreateInstanceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateInstanceHandlerFunc) Handle(params CreateInstanceParams) middleware.Responder {
	return fn(params)
}

// CreateInstanceHandler interface for that can handle valid create instance params
type CreateInstanceHandler interface {
	Handle(CreateInstanceParams) middleware.Responder
}

// NewCreateInstance creates a new http.Handler for the create instance operation
func NewCreateInstance(ctx *middleware.Context, handler CreateInstanceHandler) *CreateInstance {
	return &CreateInstance{Context: ctx, Handler: handler}
}

/*CreateInstance swagger:route POST /instance instances createInstance

Create new P2P instance

*/
type CreateInstance struct {
	Context *middleware.Context
	Handler CreateInstanceHandler
}

func (o *CreateInstance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateInstanceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
