// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Subutai P2P
Subutai P2P operations

Terms Of Service:

https://subutai.io


    Schemes:
      http
      https
    Host: localhost
    BasePath: /v1
    Version: 6.3.0
    License: GPLv3 https://www.gnu.org/licenses/gpl-3.0.en.html
    Contact: <msavochkin@optimal-dynamics.com>

    Consumes:
    - application/json
    - application/xml

    Produces:
    - application/json
    - application/xml

swagger:meta
*/
package restapi
