// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DHT d h t
// swagger:model DHT
type DHT struct {

	// endpoint
	Endpoint string `json:"endpoint,omitempty"`

	// rx
	Rx string `json:"rx,omitempty"`

	// tx
	Tx string `json:"tx,omitempty"`
}

// Validate validates this d h t
func (m *DHT) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DHT) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DHT) UnmarshalBinary(b []byte) error {
	var res DHT
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
