// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Daemon daemon
// swagger:model Daemon
type Daemon struct {

	// build
	Build string `json:"build,omitempty"`

	// dht
	Dht []*DHT `json:"dht"`

	// os
	Os string `json:"os,omitempty"`

	// uptime
	Uptime string `json:"uptime,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this daemon
func (m *Daemon) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDht(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Daemon) validateDht(formats strfmt.Registry) error {

	if swag.IsZero(m.Dht) { // not required
		return nil
	}

	for i := 0; i < len(m.Dht); i++ {

		if swag.IsZero(m.Dht[i]) { // not required
			continue
		}

		if m.Dht[i] != nil {

			if err := m.Dht[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dht" + "." + strconv.Itoa(i))
				}
				return err
			}

		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Daemon) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Daemon) UnmarshalBinary(b []byte) error {
	var res Daemon
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
